"""add application_settings table

Revision ID: 71c18e88d5f5
Revises: 3fb9f04db8fb
Create Date: 2026-08-31 20:32:58.409384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c18e88d5f5'
down_revision: Union[str, Sequence[str], None] = '3fb9f04db8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_expiring_soon_days', sa.Integer(), nullable=False),
    sa.Column('alert_critical_days', sa.Integer(), nullable=False),
    sa.Column('report_days_threshold', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
    sa.Column('smtp_from_name', sa.String(length=255), nullable=False),
    sa.Column('report_recipient_email', sa.String(length=255), nullable=True),
    sa.Column('daily_check_hour', sa.Integer(), nullable=False),
    sa.Column('daily_check_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_settings')
    # ### end Alembic commands ###
